obstacle_range: 2.5
raytrace_range: 2.5
# robot_radius: 0.23
footprint: [[-0.35, -0.25], [-0.35, 0.25], [0.35, 0.25], [0.35, -0.25]]
inflation_radius: 1
transform_tolerance: 0.6

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

map_type: costmap